ignore:

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  "Andreas Isaak <info@andreas-isaak.de>": "Andreas Isaak <andy.jared@googlemail.com>"
  "Stefan Heimes <stefan_heimes@hotmail.com>":
    - "Stefan heimes <stefan_heimes@hotmail.com>"
    - "chibineko <stefan_heimes@hotmail.com>"
    - "stefanheimes <stefan_heimes@hotmail.com>"
    - "Stefan Heimes <cms@men-at-work.de>"
  "David Maack <david.maack@arcor.de>":
    - "David Maack <maack@men-at-work.de>"
    - "davidmaack <david.maack@arcor.de>"
    - "unknown <David.Maack@pc024.men-at-work.de>"
    - "unknown <David.Maack@.men-at-work.de>"
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'zonky2 <info@e-spin.de>'
    - 'info@e-spin.de <info@e-spin.de>'
  "Fritz Michael Gschwantner <fmg@inspiredminds.at>":
    - "fritzmg <fmg@inspiredminds.at>"
    - "fritzmg <email@spikx.net>"

copy-left:
 
