ignore:

exclude:
  languages

mapping:
  "Andreas Isaak <info@andreas-isaak.de>": "Andreas Isaak <andy.jared@googlemail.com>"
  "Stefan Heimes <stefan_heimes@hotmail.com>":
    - "Stefan heimes <stefan_heimes@hotmail.com>"
    - "chibineko <stefan_heimes@hotmail.com>"
    - "stefanheimes <stefan_heimes@hotmail.com>"
    - "Stefan Heimes <cms@men-at-work.de>"
  "David Maack <david.maack@arcor.de>":
    - "David Maack <maack@men-at-work.de>"
    - "davidmaack <david.maack@arcor.de>"

copy-left:
 
